services:
  - type: web
    name: ranquiz-backend
    env: go
    root_dir: backend
    buildCommand: go mod tidy && GOOS=linux GOARCH=amd64 go build -o ranquiz-backend main.go && pip install -r requirements.txt
    startCommand: ./ranquiz-backend
    ports:
      - 8080
    envVars:
      - key: GUMELOOP_API_KEY
        sync: false # Set this value securely in Render dashboard
      - key: GUMELOOP_USER_ID
        sync: false # Set this value securely in Render dashboard
