services:
  - type: web
    name: ranquiz-backend
    env: go
    buildCommand: |
      python3 -m pip install -r requirements.txt
      go build -o ranquiz-backend
    startCommand: ./ranquiz-backend
    envVars:
      - key: PORT
        value: "8080"
      - key: GUMELOOP_API_KEY
        sync: false
      - key: GUMELOOP_USER_ID
        sync: false
      - key: GUMELOOP_FLOW_ID
        sync: false
