services:
  - type: web
    name: ranquiz-backend
    env: docker
    dockerfilePath: ./Dockerfile
    ports:
      - 8080
    envVars:
      - key: GUMELOOP_API_KEY
        sync: false
      - key: GUMELOOP_USER_ID
        sync: false
      - key: GUMELOOP_FLOW_ID
        sync: false