services:
  - type: web
    name: ranquiz-backend
    env: go
    root_dir: backend
    buildCommand: |
      go mod tidy
      GOOS=linux GOARCH=amd64 go build -o ranquiz-backend main.go
      python3 -m venv venv
      ./venv/bin/pip install -r requirements.txt
    startCommand: ./ranquiz-backend
    ports:
      - 8080
    envVars:
      - key: GUMELOOP_API_KEY
        sync: false
      - key: GUMELOOP_USER_ID
        sync: false
