services:
  - type: docker
    name: ranquiz-backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: GUMELOOP_API_KEY
        sync: false
      - key: GUMELOOP_USER_ID
        sync: false
      - key: GUMELOOP_FLOW_ID
        sync: false